variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

Run models:
  stage: build
  image: python:3.7-stretch
  # only:
  #   variables:
  #     - $DOLOS == 'True'
  script:
    - apt-get update -qq
    - apt-get install -qq r-base  # Should be in the docker image
    - pip3 install -e .[dev,survey]
    - mkdir ~/.config
    - mkdir ~/.config/openfisca-survey-manager
    - cp /home/ipp/data/openfisca-france-indirect-taxation/openfisca_survey_manager_raw_data.ini ~/.config/openfisca-survey-manager/raw_data.ini
    - cp /home/ipp/data/openfisca-france-indirect-taxation/openfisca_survey_manager_config.ini ~/.config/openfisca-survey-manager/config.ini
    - mkdir /root/ci-files
    - mkdir /root/ci-files/data_collections
    - build-collection -c budget_des_familles -d -m
    - build-collection -c aliss -m -d
    - build-collection -c enquete_logement -d -m -s 2013
    - build-collection -c enquete_transports -d -m -s 2008
    - build-collection -c erfs_fpr -d -m -s 2013
    - build-survey-data -v
    - make test
