variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

Run models:
  stage: build
  image: python:3.7-stretch
  # only:
  #   variables:
  #     - $DOLOS == 'True'
  script:
    - pip3 install .[dev,survey]
    - mkdir ~/.config
    - mkdir ~/.config/openfisca-survey-manager
    - cp /home/ipp/data/openfisca-france-indirect-taxation/openfisca_survey_manager_raw_data.ini ~/.config/openfisca-survey-manager/raw_data.ini
    - cp /home/ipp/data/openfisca-france-indirect-taxation/openfisca_survey_manager_config.ini ~/.config/openfisca-survey-manager/config.ini
    - mkdir /root/ci-files
    - mkdir /root/ci-files/data_collections
    - build-collection -c budget_des_familles -d -m
    - build-survey-data -v
    - make test
