stages:
  - build_docker_image
  - build_collections
  - build_matched_data
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

Build Docker image:
  stage: build_docker_image
  only:
    changes:
      - Dockerfile.ci
    refs:
      - ultimate_migration
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.ci --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

Build survey collections:
  stage: build_collections
  image: $CI_REGISTRY_IMAGE:latest
  tags:
    - ipp
  before_script:
    - mkdir -p ~/.config/openfisca-survey-manager
    - cp ./runner/openfisca_survey_manager_raw_data.ini ~/.config/openfisca-survey-manager/raw_data.ini
    - cp ./runner/openfisca_survey_manager_config.ini ~/.config/openfisca-survey-manager/config.ini
    - mkdir -p /root/ci-files/data_collections
    - pip3 install -e .[dev,survey]
  script:
    - build-collection -c budget_des_familles -d -m
    - build-collection -c aliss -m -d
    - build-collection -c enquete_logement -d -m -s 2013
    - build-collection -c enquete_transports -d -m -s 2008
    - build-collection -c erfs_fpr -d -m -s 2013
    - cp ~/.config/openfisca-survey-manager/config.ini  /home/ipp/data/openfisca-france-indirect-taxation/openfisca_survey_manager_config.ini
  when: manual

Build matched data:
  stage: build_matched_data
  image: $CI_REGISTRY_IMAGE:latest
  tags:
    - ipp
  before_script:
    - mkdir -p ~/.config/openfisca-survey-manager
    - pip3 install -e .[dev,survey]
    - cp ./runner/openfisca_survey_manager_raw_data.ini ~/.config/openfisca-survey-manager/raw_data.ini
    - cp /home/ipp/data/openfisca-france-indirect-taxation/openfisca_survey_manager_config.ini ~/.config/openfisca-survey-manager/config.ini
    - mkdir -p /root/ci-files/data_collections
  script:
    - build-survey-data -v
  when: manual

Test:
  stage: test
  image: $CI_REGISTRY_IMAGE:latest
  tags:
    - ipp
  before_script:
    - mkdir -p ~/.config/openfisca-survey-manager
    - pip3 install -e .[dev,survey]
    - cp ./runner/openfisca_survey_manager_raw_data.ini ~/.config/openfisca-survey-manager/raw_data.ini
    - cp /home/ipp/data/openfisca-france-indirect-taxation/openfisca_survey_manager_config.ini ~/.config/openfisca-survey-manager/config.ini
    - mkdir -p /root/ci-files/data_collections
  script:
    - make test
