addons:
  apt:
    packages:
    - python-numpy
    - python-yaml
    - python-pandas
language: python
python: "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo add-apt-repository ppa:pylab/stable -y  # For SciPY
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev liblzo2-dev libbz2-dev
install:
  - pip install flake8  # Not yet available in Debian stable
  - pip install xlrd --upgrade
  - pip install -r requirements.txt

script: make test-ci
