language: python
python: "2.7"
virtualenv:
  system_site_packages: true
# before_install:
#   - sudo add-apt-repository ppa:pylab/stable -y  # For SciPY
#   - sudo apt-get update -qq
#   - sudo apt-get install -qq libhdf5-serial-dev liblzo2-dev libbz2-dev
install:
 # Install conda
  - sudo pip install conda
  # install deps
  - sudo conda init
  - sudo conda update conda --yes
  - deps='pip numpy pandas python-yaml'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - pip install flake8  # Not yet available in Debian stable
  - pip install xlrd --upgrade
  - pip install -r requirements.txt

script: make test-ci
