description: TICPE - produits énergétiques a
goudrons_utilises_comme_combustibles_100kg:
  description: Goudrons utilisés comme combustibles, (100kg)
  values:
    2018-01-01:
      value: 10.08
    2017-01-01:
      value: 6.89
    2016-01-01:
      value: 4.97
    2015-01-01:
      value: 3.28
    2014-04-01:
      value: 1.58
    2008-01-01:
      value: 1.5
    2002-01-01:
      value: 1.22
    2000-01-01:
      value: 8.03
    1999-01-01:
      value: 7.99
    1998-01-01:
      value: 7.92
    1997-01-01:
      value: 7.82
    1996-01-01:
      value: 7.66
    1995-01-01:
      value: 7.52
    1994-01-01:
      value: 7.39
    1993-04-15:
      value: 6.65
    1993-01-01:
      value: null
  metadata:
    ipp_csv_id: ticpe_goudron_combustible
    unit:
      2002-01-01: currency-EUR
      1993-04-15: currency-FRF
white_spirit_utilise_comme_combustible_hectolitre:
  description: White Spirit utilisé comme combustible (hectolitre)
  values:
    2018-01-01:
      value: 15.25
    2017-01-01:
      value: 12.02
    2016-01-01:
      value: 10.08
    2015-01-01:
      value: 7.87
    2003-01-01:
      value: 5.66
    2002-01-01:
      value: 5.49
    2000-01-01:
      value: 51.73
    1993-01-01:
      value: null
  metadata:
    ipp_csv_id: ticpe_white_spirit_combustible
    unit:
      2002-01-01: currency-EUR
      2000-01-01: currency-FRF
essences_speciales_utilisees_comme_carburants_combustibles_hectolitre:
  description: Essences spéciales utilisées comme carburants et combustibles (hectolitre)
  values:
    2018-01-01:
      value: 67.52
    2017-01-01:
      value: 64.3
    2016-01-01:
      value: 62.35
    2015-01-01:
      value: 60.64
    2008-01-01:
      value: 58.92
    2006-01-01:
      value: 60.69
    2003-01-01:
      value: 58.92
    2002-01-01:
      value: 58.63
    2000-01-01:
      value: 384.62
    1999-01-01:
      value: 398.86
    1998-01-01:
      value: 394.92
    1997-01-01:
      value: 386.92
    1996-01-01:
      value: 380.92
    1995-01-01:
      value: 367.92
    1994-01-01:
      value: 347.41
    1993-04-15:
      value: 311.25
    1993-01-01:
      value: null
  metadata:
    ipp_csv_id: ticpe_essences_speciales
    unit:
      2002-01-01: currency-EUR
      1993-04-15: currency-FRF
huiles_legeres_preparation_essence_aviation_hectolitre:
  description: Huiles légères et préparation, essence d'aviation (hectolitre)
  values:
    2018-01-01:
      value: 45.49
    2017-01-01:
      value: 41.89
    2016-01-01:
      value: 39.72
    2015-01-01:
      value: 37.81
    2008-01-01:
      value: 35.9
    2002-01-01:
      value: 32.36
    2000-01-01:
      value: 212.25
    1999-01-01:
      value: 211.19
    1998-01-01:
      value: 209.31
    1997-01-01:
      value: 206.82
    1996-01-01:
      value: 202.37
    1995-01-01:
      value: 198.6
    1994-01-01:
      value: 195.28
    1993-04-15:
      value: 175.82
    1993-01-01:
      value: null
  metadata:
    ipp_csv_id: ticpe_huiles_legeres_ess_avion
    unit:
      2002-01-01: currency-EUR
      1993-04-15: currency-FRF
supercarburants_dont_sp95_sp98_hectolitre:
  description: Supercarburants dont SP95 et SP98 (hectolitre)*
  values:
    2018-01-01:
      value: 68.29
    2017-01-01:
      value: 65.07
    2016-01-01:
      value: 64.12
    2015-01-01:
      value: 62.41
    2006-01-01:
      value: 60.69
    2003-01-01:
      value: 58.92
    2002-01-01:
      value: 58.63
    1999-01-01:
      value: 384.62
    1998-01-01:
      value: 384.23
    1997-01-01:
      value: 376.23
    1996-01-01:
      value: 370.23
    1995-01-01:
      value: 357.23
    1994-01-01:
      value: 329.5
    1993-04-15:
      value: 290.12
    1993-01-01:
      value: null
  metadata:
    ipp_csv_id: ticpe_sp95_sp98
    unit:
      2002-01-01: currency-EUR
      1993-04-15: currency-FRF
supercarburants_contenant_additif_hectolitre:
  description: Supercarburants contenant un additif (hectolitre)
  values:
    2018-01-01:
      value: 71.56
    2017-01-01:
      value: 68.34
    2016-01-01:
      value: 67.39
    2015-01-01:
      value: 65.68
    2003-01-01:
      value: 63.96
    2002-01-01:
      value: 63.67
    2000-01-01:
      value: 417.68
    1999-01-01:
      value: 415.5
    1998-01-01:
      value: 411.51
    1997-01-01:
      value: 403.51
    1996-01-01:
      value: 396.51
    1995-01-01:
      value: 383.51
    1994-01-01:
      value: 363.0
    1993-04-15:
      value: 326.84
    1993-01-01:
      value: null
  metadata:
    ipp_csv_id: ticpe_super_additif
    unit:
      2002-01-01: currency-EUR
      1993-04-15: currency-FRF
supere10_hectolitre:
  description: SuperE10 (hectolitre) *
  values:
    2018-01-01:
      value: 66.29
    2017-01-01:
      value: 63.07
    2016-01-01:
      value: 62.12
    2015-01-01:
      value: 62.41
    2008-12-29:
      value: 60.69
    1993-01-01:
      value: null
  metadata:
    ipp_csv_id: ticpe_super_e10
    unit: currency-EUR
essence_normale_hectolitre:
  description: Essence normale (hectolitre)
  values:
    2000-01-01:
      value: null
    1999-01-01:
      value: 398.86
    1998-01-01:
      value: 394.92
    1997-01-01:
      value: 386.92
    1996-01-01:
      value: 380.92
    1995-01-01:
      value: 367.92
    1994-01-01:
      value: 347.41
    1993-04-15:
      value: 311.25
    1993-01-01:
      value: null
  metadata:
    ipp_csv_id: ticpe_essence_normale
    unit: currency-FRF
metadata:
  order:
  - goudrons_utilises_comme_combustibles_100kg
  - white_spirit_utilise_comme_combustible_hectolitre
  - essences_speciales_utilisees_comme_carburants_combustibles_hectolitre
  - huiles_legeres_preparation_essence_aviation_hectolitre
  - supercarburants_dont_sp95_sp98_hectolitre
  - supercarburants_contenant_additif_hectolitre
  - supere10_hectolitre
  - essence_normale_hectolitre
  reference:
    2018-01-01:
      title: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000036339197
    2017-01-01:
      title: Loi 2016-1918 du 29/12/2016 (LFR pour 2016)
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000033734341
    2016-01-01: Loi 2015-1786 du 29/12/2015 (LFR pour 2015) - art. 14 et 17
    2015-01-01:
      title: Loi 2014-1654 du 29/12/2014 (LF pour 2015) - art. 36
      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000029994876&cidTexte=JORFTEXT000029988857
    2014-04-01:
      title: Loi 2013-1278 du 29/12/2013 (LF pour 2014) - art. 32
      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000028402549&cidTexte=JORFTEXT000028399511
    2012-01-01:
      title: Loi 2011-1977 du 28/12/2011 (LF pour 2012) - art. 21
      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000025048278&cidTexte=JORFTEXT000025044460
    2011-01-01:
      title: Loi 2010-1657 du 29/12/2010 (LF pour 2011) - art. 138
      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000023347209&cidTexte=JORFTEXT000023314376
    2010-03-11: Loi 2010-237 du 09/03/2010 (LFR pour 2010) - art. 4 et 5
    2010-01-01:
      title: Loi 2009-1674 du 30/12/2009 (LFR pour 2009) - art. 76
      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000021580225&cidTexte=JORFTEXT000021559075
    2009-01-01:
      title: Loi 2008-1443 du 30/12/2008 (LFR pour 2008)
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000020014790
    2008-12-29: Loi 2008-1425 du 27/12/2008 (LF pour 2009)  - art. 16 et 17
    2008-01-01:
      title: Loi 2007-1822 du 24/12/2007 (LF pour 2008)
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000017853368
    2006-01-01:
      title: Loi 2004-1484 du 30/12/2004 (LF pour 2005)
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000789373
    2004-01-01:
      title: Loi 2003-1311 du 30/12/2003 (LF pour 2004)
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000612133
    2003-01-01:
      title: Loi 2002-1575 du 30/12/2002 (LF pour 2003)
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000234121
    2002-01-01:
      title: Loi 2001-1275 du 28/12/2001 (LF pour 2002)
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000592233
    2000-01-01:
      title: Loi 99-1172 du 30/12/1999 (LF pour 2000)
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000762233
    1999-01-01:
      title: Loi 98-1266 du 30/12/1998 (LF pour 1999)
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000209044
    1998-01-01:
      title: Loi 97-1269 du 30/12/1997 (LF pour 1998)
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000569621
    1997-01-01:
      title: Loi 96-1181 du 30/12/1996 (LF pour 1997)
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000380034
    1996-01-01:
      title: Loi 95-1346 du 30/12/1995 (LF pour 1996)
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000191068
    1995-01-01:
      title: Loi 94-1162 du 29/12/1994 (LF pour 1995)
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000367398
    1994-01-01:
      title: Loi 93-1352 du 30/12/1993 (LF pour 1994)
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000509319
    1993-04-15:
      title: Loi 92-1376 du 30/12/1992 (LF pour 1993)
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000178406
    1993-01-01:
      title: Loi 92-1376 du 30/12/1992 (LF pour 1993)
      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000178406
  date_parution_jo:
    2018-01-01: 2017-12-31
    2017-01-01: 2016-12-30
    2016-01-01: 2015-12-30
    2015-01-01: 2014-12-30
    2014-04-01: 2013-12-30
    2012-01-01: 2011-12-29
    2011-01-01: 2010-12-30
    2010-03-11: 2010-03-10
    2010-01-01: 2009-12-31
    2009-01-01: 2008-12-31
    2008-12-29: 2008-12-28
    2008-01-01: 2007-12-27
    2006-01-01: 2004-12-31
    2004-01-01: 2003-12-31
    2003-01-01: 2002-12-31
    2002-01-01: 2001-12-29
    2000-01-01: 1999-12-31
    1999-01-01: 1998-12-31
    1998-01-01: 1997-12-31
    1997-01-01: 1996-12-31
    1996-01-01: 1995-12-31
    1995-01-01: 1994-12-30
    1994-01-01: 1993-12-31
    1993-04-15: 1992-12-31
    1993-01-01: 1992-12-31
  description_en: TICPE - Energy products a
documentation: |
  Notes :
  *ces barèmes font l'objet de majorations dans la plupart des régions de France : une première tranche de 1,77€/hl puis une seconde de 0,73€/hl (deuxième tranche destinée uniquement à des financements d'infrastructures spécifiques
  NB : données renseignées dans l'article 265 du code des douanes
  NB : les produits énergétiques sont rangés de a à e dans l'ordre de leur numérotation dans l'article 265 du code des douanes. Cette séparation en cinq onglets a pour seul objectif la lisibilité.
  NB : en 2011 le nom de TIPP (taxe intérieure de consommation sur les produits pétroliers) change pour TICPE (taxe intérieure de consommation sur les produits énergétiques). L'objectif est de souligner le changement d'assiette récent qui incorpore désormais les biocarburants.
  Attention : 28 aout 2012, baisse de la TICPE sur les carburants de 3 centimes. La baisse est ramenée à 2 centimes le 1er décembre 2012, 1,5c le 11 décembre, 1c le 21 décembre et prend fin le 11 janvier 2013
  Dans le code des douanes, les produits énergétiques sont désignés par les indices suivants :
  1 - Goudrons utilisés comme combustibles
  4 bis - White Spirit utilisé comme combustible
  6 - essences spéciales utilisées comme carburants et combustibles
  10 - huiles légères et préparation, essence d'aviation
  11 - supercarburants dont SP95 et SP98
  11 bis - supercarburants contenant un additif
  11 ter - superE10
  12 - essence normale
